

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "time",
    srcs = [
        "timer.cc",
    ],
    hdrs = [
        "time.h",
        "time_util.h",
        "timer.h",
    ],
    deps = [
        "//modules/common:log",
        "//modules/common:macro",
        "//modules/common/configs:config_gflags",
        "@ros//:ros_common",
    ],
)




