// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/perception/proto/perception_obstacle.proto

#ifndef PROTOBUF_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto__INCLUDED
#define PROTOBUF_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "modules/common/proto/error_code.pb.h"
#include "modules/common/proto/header.pb.h"
#include "modules/map/proto/map_lane.pb.h"
// @@protoc_insertion_point(includes)

namespace apollo {
namespace perception {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
void protobuf_AssignDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
void protobuf_ShutdownFile_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();

class CIPVInfo;
class LaneMarker;
class LaneMarkers;
class PerceptionObstacle;
class PerceptionObstacles;
class Point;

enum PerceptionObstacle_Type {
  PerceptionObstacle_Type_UNKNOWN = 0,
  PerceptionObstacle_Type_UNKNOWN_MOVABLE = 1,
  PerceptionObstacle_Type_UNKNOWN_UNMOVABLE = 2,
  PerceptionObstacle_Type_PEDESTRIAN = 3,
  PerceptionObstacle_Type_BICYCLE = 4,
  PerceptionObstacle_Type_VEHICLE = 5
};
bool PerceptionObstacle_Type_IsValid(int value);
const PerceptionObstacle_Type PerceptionObstacle_Type_Type_MIN = PerceptionObstacle_Type_UNKNOWN;
const PerceptionObstacle_Type PerceptionObstacle_Type_Type_MAX = PerceptionObstacle_Type_VEHICLE;
const int PerceptionObstacle_Type_Type_ARRAYSIZE = PerceptionObstacle_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* PerceptionObstacle_Type_descriptor();
inline const ::std::string& PerceptionObstacle_Type_Name(PerceptionObstacle_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    PerceptionObstacle_Type_descriptor(), value);
}
inline bool PerceptionObstacle_Type_Parse(
    const ::std::string& name, PerceptionObstacle_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PerceptionObstacle_Type>(
    PerceptionObstacle_Type_descriptor(), name, value);
}
enum PerceptionObstacle_ConfidenceType {
  PerceptionObstacle_ConfidenceType_CONFIDENCE_UNKNOWN = 0,
  PerceptionObstacle_ConfidenceType_CONFIDENCE_CNN = 1,
  PerceptionObstacle_ConfidenceType_CONFIDENCE_RADAR = 2
};
bool PerceptionObstacle_ConfidenceType_IsValid(int value);
const PerceptionObstacle_ConfidenceType PerceptionObstacle_ConfidenceType_ConfidenceType_MIN = PerceptionObstacle_ConfidenceType_CONFIDENCE_UNKNOWN;
const PerceptionObstacle_ConfidenceType PerceptionObstacle_ConfidenceType_ConfidenceType_MAX = PerceptionObstacle_ConfidenceType_CONFIDENCE_RADAR;
const int PerceptionObstacle_ConfidenceType_ConfidenceType_ARRAYSIZE = PerceptionObstacle_ConfidenceType_ConfidenceType_MAX + 1;

const ::google::protobuf::EnumDescriptor* PerceptionObstacle_ConfidenceType_descriptor();
inline const ::std::string& PerceptionObstacle_ConfidenceType_Name(PerceptionObstacle_ConfidenceType value) {
  return ::google::protobuf::internal::NameOfEnum(
    PerceptionObstacle_ConfidenceType_descriptor(), value);
}
inline bool PerceptionObstacle_ConfidenceType_Parse(
    const ::std::string& name, PerceptionObstacle_ConfidenceType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PerceptionObstacle_ConfidenceType>(
    PerceptionObstacle_ConfidenceType_descriptor(), name, value);
}
// ===================================================================

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  void Swap(Point* other);

  // implements Message ----------------------------------------------

  inline Point* New() const { return New(NULL); }

  Point* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // @@protoc_insertion_point(class_scope:apollo.perception.Point)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  friend void  protobuf_AddDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_AssignDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_ShutdownFile_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();

  void InitAsDefaultInstance();
  static Point* default_instance_;
};
// -------------------------------------------------------------------

class PerceptionObstacle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.PerceptionObstacle) */ {
 public:
  PerceptionObstacle();
  virtual ~PerceptionObstacle();

  PerceptionObstacle(const PerceptionObstacle& from);

  inline PerceptionObstacle& operator=(const PerceptionObstacle& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PerceptionObstacle& default_instance();

  void Swap(PerceptionObstacle* other);

  // implements Message ----------------------------------------------

  inline PerceptionObstacle* New() const { return New(NULL); }

  PerceptionObstacle* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PerceptionObstacle& from);
  void MergeFrom(const PerceptionObstacle& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PerceptionObstacle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef PerceptionObstacle_Type Type;
  static const Type UNKNOWN =
    PerceptionObstacle_Type_UNKNOWN;
  static const Type UNKNOWN_MOVABLE =
    PerceptionObstacle_Type_UNKNOWN_MOVABLE;
  static const Type UNKNOWN_UNMOVABLE =
    PerceptionObstacle_Type_UNKNOWN_UNMOVABLE;
  static const Type PEDESTRIAN =
    PerceptionObstacle_Type_PEDESTRIAN;
  static const Type BICYCLE =
    PerceptionObstacle_Type_BICYCLE;
  static const Type VEHICLE =
    PerceptionObstacle_Type_VEHICLE;
  static inline bool Type_IsValid(int value) {
    return PerceptionObstacle_Type_IsValid(value);
  }
  static const Type Type_MIN =
    PerceptionObstacle_Type_Type_MIN;
  static const Type Type_MAX =
    PerceptionObstacle_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    PerceptionObstacle_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return PerceptionObstacle_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return PerceptionObstacle_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return PerceptionObstacle_Type_Parse(name, value);
  }

  typedef PerceptionObstacle_ConfidenceType ConfidenceType;
  static const ConfidenceType CONFIDENCE_UNKNOWN =
    PerceptionObstacle_ConfidenceType_CONFIDENCE_UNKNOWN;
  static const ConfidenceType CONFIDENCE_CNN =
    PerceptionObstacle_ConfidenceType_CONFIDENCE_CNN;
  static const ConfidenceType CONFIDENCE_RADAR =
    PerceptionObstacle_ConfidenceType_CONFIDENCE_RADAR;
  static inline bool ConfidenceType_IsValid(int value) {
    return PerceptionObstacle_ConfidenceType_IsValid(value);
  }
  static const ConfidenceType ConfidenceType_MIN =
    PerceptionObstacle_ConfidenceType_ConfidenceType_MIN;
  static const ConfidenceType ConfidenceType_MAX =
    PerceptionObstacle_ConfidenceType_ConfidenceType_MAX;
  static const int ConfidenceType_ARRAYSIZE =
    PerceptionObstacle_ConfidenceType_ConfidenceType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ConfidenceType_descriptor() {
    return PerceptionObstacle_ConfidenceType_descriptor();
  }
  static inline const ::std::string& ConfidenceType_Name(ConfidenceType value) {
    return PerceptionObstacle_ConfidenceType_Name(value);
  }
  static inline bool ConfidenceType_Parse(const ::std::string& name,
      ConfidenceType* value) {
    return PerceptionObstacle_ConfidenceType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // optional .apollo.perception.Point position = 2;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 2;
  const ::apollo::perception::Point& position() const;
  ::apollo::perception::Point* mutable_position();
  ::apollo::perception::Point* release_position();
  void set_allocated_position(::apollo::perception::Point* position);

  // optional double theta = 3;
  bool has_theta() const;
  void clear_theta();
  static const int kThetaFieldNumber = 3;
  double theta() const;
  void set_theta(double value);

  // optional .apollo.perception.Point velocity = 4;
  bool has_velocity() const;
  void clear_velocity();
  static const int kVelocityFieldNumber = 4;
  const ::apollo::perception::Point& velocity() const;
  ::apollo::perception::Point* mutable_velocity();
  ::apollo::perception::Point* release_velocity();
  void set_allocated_velocity(::apollo::perception::Point* velocity);

  // optional double length = 5;
  bool has_length() const;
  void clear_length();
  static const int kLengthFieldNumber = 5;
  double length() const;
  void set_length(double value);

  // optional double width = 6;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 6;
  double width() const;
  void set_width(double value);

  // optional double height = 7;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 7;
  double height() const;
  void set_height(double value);

  // repeated .apollo.perception.Point polygon_point = 8;
  int polygon_point_size() const;
  void clear_polygon_point();
  static const int kPolygonPointFieldNumber = 8;
  const ::apollo::perception::Point& polygon_point(int index) const;
  ::apollo::perception::Point* mutable_polygon_point(int index);
  ::apollo::perception::Point* add_polygon_point();
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >*
      mutable_polygon_point();
  const ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >&
      polygon_point() const;

  // optional double tracking_time = 9;
  bool has_tracking_time() const;
  void clear_tracking_time();
  static const int kTrackingTimeFieldNumber = 9;
  double tracking_time() const;
  void set_tracking_time(double value);

  // optional .apollo.perception.PerceptionObstacle.Type type = 10;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 10;
  ::apollo::perception::PerceptionObstacle_Type type() const;
  void set_type(::apollo::perception::PerceptionObstacle_Type value);

  // optional double timestamp = 11;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 11;
  double timestamp() const;
  void set_timestamp(double value);

  // repeated double point_cloud = 12 [packed = true];
  int point_cloud_size() const;
  void clear_point_cloud();
  static const int kPointCloudFieldNumber = 12;
  double point_cloud(int index) const;
  void set_point_cloud(int index, double value);
  void add_point_cloud(double value);
  const ::google::protobuf::RepeatedField< double >&
      point_cloud() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_point_cloud();

  // optional double confidence = 13 [default = 1];
  bool has_confidence() const;
  void clear_confidence();
  static const int kConfidenceFieldNumber = 13;
  double confidence() const;
  void set_confidence(double value);

  // optional .apollo.perception.PerceptionObstacle.ConfidenceType confidence_type = 14 [default = CONFIDENCE_CNN];
  bool has_confidence_type() const;
  void clear_confidence_type();
  static const int kConfidenceTypeFieldNumber = 14;
  ::apollo::perception::PerceptionObstacle_ConfidenceType confidence_type() const;
  void set_confidence_type(::apollo::perception::PerceptionObstacle_ConfidenceType value);

  // repeated .apollo.perception.Point drops = 15;
  int drops_size() const;
  void clear_drops();
  static const int kDropsFieldNumber = 15;
  const ::apollo::perception::Point& drops(int index) const;
  ::apollo::perception::Point* mutable_drops(int index);
  ::apollo::perception::Point* add_drops();
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >*
      mutable_drops();
  const ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >&
      drops() const;

  // @@protoc_insertion_point(class_scope:apollo.perception.PerceptionObstacle)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_theta();
  inline void clear_has_theta();
  inline void set_has_velocity();
  inline void clear_has_velocity();
  inline void set_has_length();
  inline void clear_has_length();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_tracking_time();
  inline void clear_has_tracking_time();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_confidence();
  inline void clear_has_confidence();
  inline void set_has_confidence_type();
  inline void clear_has_confidence_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::perception::Point* position_;
  double theta_;
  ::apollo::perception::Point* velocity_;
  double length_;
  ::google::protobuf::int32 id_;
  int type_;
  double width_;
  double height_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point > polygon_point_;
  double tracking_time_;
  double timestamp_;
  ::google::protobuf::RepeatedField< double > point_cloud_;
  mutable int _point_cloud_cached_byte_size_;
  double confidence_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point > drops_;
  int confidence_type_;
  friend void  protobuf_AddDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_AssignDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_ShutdownFile_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();

  void InitAsDefaultInstance();
  static PerceptionObstacle* default_instance_;
};
// -------------------------------------------------------------------

class CIPVInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.CIPVInfo) */ {
 public:
  CIPVInfo();
  virtual ~CIPVInfo();

  CIPVInfo(const CIPVInfo& from);

  inline CIPVInfo& operator=(const CIPVInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CIPVInfo& default_instance();

  void Swap(CIPVInfo* other);

  // implements Message ----------------------------------------------

  inline CIPVInfo* New() const { return New(NULL); }

  CIPVInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CIPVInfo& from);
  void MergeFrom(const CIPVInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CIPVInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 cipv_id = 1;
  bool has_cipv_id() const;
  void clear_cipv_id();
  static const int kCipvIdFieldNumber = 1;
  ::google::protobuf::int32 cipv_id() const;
  void set_cipv_id(::google::protobuf::int32 value);

  // repeated int32 potential_cipv_id = 2;
  int potential_cipv_id_size() const;
  void clear_potential_cipv_id();
  static const int kPotentialCipvIdFieldNumber = 2;
  ::google::protobuf::int32 potential_cipv_id(int index) const;
  void set_potential_cipv_id(int index, ::google::protobuf::int32 value);
  void add_potential_cipv_id(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      potential_cipv_id() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_potential_cipv_id();

  // @@protoc_insertion_point(class_scope:apollo.perception.CIPVInfo)
 private:
  inline void set_has_cipv_id();
  inline void clear_has_cipv_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > potential_cipv_id_;
  ::google::protobuf::int32 cipv_id_;
  friend void  protobuf_AddDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_AssignDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_ShutdownFile_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();

  void InitAsDefaultInstance();
  static CIPVInfo* default_instance_;
};
// -------------------------------------------------------------------

class LaneMarker : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.LaneMarker) */ {
 public:
  LaneMarker();
  virtual ~LaneMarker();

  LaneMarker(const LaneMarker& from);

  inline LaneMarker& operator=(const LaneMarker& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LaneMarker& default_instance();

  void Swap(LaneMarker* other);

  // implements Message ----------------------------------------------

  inline LaneMarker* New() const { return New(NULL); }

  LaneMarker* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LaneMarker& from);
  void MergeFrom(const LaneMarker& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LaneMarker* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.hdmap.LaneBoundaryType.Type lane_type = 1;
  bool has_lane_type() const;
  void clear_lane_type();
  static const int kLaneTypeFieldNumber = 1;
  ::apollo::hdmap::LaneBoundaryType_Type lane_type() const;
  void set_lane_type(::apollo::hdmap::LaneBoundaryType_Type value);

  // optional double quality = 2;
  bool has_quality() const;
  void clear_quality();
  static const int kQualityFieldNumber = 2;
  double quality() const;
  void set_quality(double value);

  // optional int32 model_degree = 3;
  bool has_model_degree() const;
  void clear_model_degree();
  static const int kModelDegreeFieldNumber = 3;
  ::google::protobuf::int32 model_degree() const;
  void set_model_degree(::google::protobuf::int32 value);

  // optional double c0_position = 4;
  bool has_c0_position() const;
  void clear_c0_position();
  static const int kC0PositionFieldNumber = 4;
  double c0_position() const;
  void set_c0_position(double value);

  // optional double c1_heading_angle = 5;
  bool has_c1_heading_angle() const;
  void clear_c1_heading_angle();
  static const int kC1HeadingAngleFieldNumber = 5;
  double c1_heading_angle() const;
  void set_c1_heading_angle(double value);

  // optional double c2_curvature = 6;
  bool has_c2_curvature() const;
  void clear_c2_curvature();
  static const int kC2CurvatureFieldNumber = 6;
  double c2_curvature() const;
  void set_c2_curvature(double value);

  // optional double c3_curvature_derivative = 7;
  bool has_c3_curvature_derivative() const;
  void clear_c3_curvature_derivative();
  static const int kC3CurvatureDerivativeFieldNumber = 7;
  double c3_curvature_derivative() const;
  void set_c3_curvature_derivative(double value);

  // optional double view_range = 8;
  bool has_view_range() const;
  void clear_view_range();
  static const int kViewRangeFieldNumber = 8;
  double view_range() const;
  void set_view_range(double value);

  // optional double longitude_start = 9;
  bool has_longitude_start() const;
  void clear_longitude_start();
  static const int kLongitudeStartFieldNumber = 9;
  double longitude_start() const;
  void set_longitude_start(double value);

  // optional double longitude_end = 10;
  bool has_longitude_end() const;
  void clear_longitude_end();
  static const int kLongitudeEndFieldNumber = 10;
  double longitude_end() const;
  void set_longitude_end(double value);

  // @@protoc_insertion_point(class_scope:apollo.perception.LaneMarker)
 private:
  inline void set_has_lane_type();
  inline void clear_has_lane_type();
  inline void set_has_quality();
  inline void clear_has_quality();
  inline void set_has_model_degree();
  inline void clear_has_model_degree();
  inline void set_has_c0_position();
  inline void clear_has_c0_position();
  inline void set_has_c1_heading_angle();
  inline void clear_has_c1_heading_angle();
  inline void set_has_c2_curvature();
  inline void clear_has_c2_curvature();
  inline void set_has_c3_curvature_derivative();
  inline void clear_has_c3_curvature_derivative();
  inline void set_has_view_range();
  inline void clear_has_view_range();
  inline void set_has_longitude_start();
  inline void clear_has_longitude_start();
  inline void set_has_longitude_end();
  inline void clear_has_longitude_end();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double quality_;
  int lane_type_;
  ::google::protobuf::int32 model_degree_;
  double c0_position_;
  double c1_heading_angle_;
  double c2_curvature_;
  double c3_curvature_derivative_;
  double view_range_;
  double longitude_start_;
  double longitude_end_;
  friend void  protobuf_AddDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_AssignDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_ShutdownFile_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();

  void InitAsDefaultInstance();
  static LaneMarker* default_instance_;
};
// -------------------------------------------------------------------

class LaneMarkers : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.LaneMarkers) */ {
 public:
  LaneMarkers();
  virtual ~LaneMarkers();

  LaneMarkers(const LaneMarkers& from);

  inline LaneMarkers& operator=(const LaneMarkers& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LaneMarkers& default_instance();

  void Swap(LaneMarkers* other);

  // implements Message ----------------------------------------------

  inline LaneMarkers* New() const { return New(NULL); }

  LaneMarkers* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LaneMarkers& from);
  void MergeFrom(const LaneMarkers& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LaneMarkers* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.perception.LaneMarker left_lane_marker = 1;
  bool has_left_lane_marker() const;
  void clear_left_lane_marker();
  static const int kLeftLaneMarkerFieldNumber = 1;
  const ::apollo::perception::LaneMarker& left_lane_marker() const;
  ::apollo::perception::LaneMarker* mutable_left_lane_marker();
  ::apollo::perception::LaneMarker* release_left_lane_marker();
  void set_allocated_left_lane_marker(::apollo::perception::LaneMarker* left_lane_marker);

  // optional .apollo.perception.LaneMarker right_lane_marker = 2;
  bool has_right_lane_marker() const;
  void clear_right_lane_marker();
  static const int kRightLaneMarkerFieldNumber = 2;
  const ::apollo::perception::LaneMarker& right_lane_marker() const;
  ::apollo::perception::LaneMarker* mutable_right_lane_marker();
  ::apollo::perception::LaneMarker* release_right_lane_marker();
  void set_allocated_right_lane_marker(::apollo::perception::LaneMarker* right_lane_marker);

  // repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;
  int next_left_lane_marker_size() const;
  void clear_next_left_lane_marker();
  static const int kNextLeftLaneMarkerFieldNumber = 3;
  const ::apollo::perception::LaneMarker& next_left_lane_marker(int index) const;
  ::apollo::perception::LaneMarker* mutable_next_left_lane_marker(int index);
  ::apollo::perception::LaneMarker* add_next_left_lane_marker();
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker >*
      mutable_next_left_lane_marker();
  const ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker >&
      next_left_lane_marker() const;

  // repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;
  int next_right_lane_marker_size() const;
  void clear_next_right_lane_marker();
  static const int kNextRightLaneMarkerFieldNumber = 4;
  const ::apollo::perception::LaneMarker& next_right_lane_marker(int index) const;
  ::apollo::perception::LaneMarker* mutable_next_right_lane_marker(int index);
  ::apollo::perception::LaneMarker* add_next_right_lane_marker();
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker >*
      mutable_next_right_lane_marker();
  const ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker >&
      next_right_lane_marker() const;

  // @@protoc_insertion_point(class_scope:apollo.perception.LaneMarkers)
 private:
  inline void set_has_left_lane_marker();
  inline void clear_has_left_lane_marker();
  inline void set_has_right_lane_marker();
  inline void clear_has_right_lane_marker();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::perception::LaneMarker* left_lane_marker_;
  ::apollo::perception::LaneMarker* right_lane_marker_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker > next_left_lane_marker_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker > next_right_lane_marker_;
  friend void  protobuf_AddDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_AssignDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_ShutdownFile_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();

  void InitAsDefaultInstance();
  static LaneMarkers* default_instance_;
};
// -------------------------------------------------------------------

class PerceptionObstacles : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.PerceptionObstacles) */ {
 public:
  PerceptionObstacles();
  virtual ~PerceptionObstacles();

  PerceptionObstacles(const PerceptionObstacles& from);

  inline PerceptionObstacles& operator=(const PerceptionObstacles& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PerceptionObstacles& default_instance();

  void Swap(PerceptionObstacles* other);

  // implements Message ----------------------------------------------

  inline PerceptionObstacles* New() const { return New(NULL); }

  PerceptionObstacles* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PerceptionObstacles& from);
  void MergeFrom(const PerceptionObstacles& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PerceptionObstacles* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.perception.PerceptionObstacle perception_obstacle = 1;
  int perception_obstacle_size() const;
  void clear_perception_obstacle();
  static const int kPerceptionObstacleFieldNumber = 1;
  const ::apollo::perception::PerceptionObstacle& perception_obstacle(int index) const;
  ::apollo::perception::PerceptionObstacle* mutable_perception_obstacle(int index);
  ::apollo::perception::PerceptionObstacle* add_perception_obstacle();
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::PerceptionObstacle >*
      mutable_perception_obstacle();
  const ::google::protobuf::RepeatedPtrField< ::apollo::perception::PerceptionObstacle >&
      perception_obstacle() const;

  // optional .apollo.common.Header header = 2;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 2;
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* mutable_header();
  ::apollo::common::Header* release_header();
  void set_allocated_header(::apollo::common::Header* header);

  // optional .apollo.common.ErrorCode error_code = 3 [default = OK];
  bool has_error_code() const;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 3;
  ::apollo::common::ErrorCode error_code() const;
  void set_error_code(::apollo::common::ErrorCode value);

  // optional .apollo.perception.LaneMarkers lane_marker = 4;
  bool has_lane_marker() const;
  void clear_lane_marker();
  static const int kLaneMarkerFieldNumber = 4;
  const ::apollo::perception::LaneMarkers& lane_marker() const;
  ::apollo::perception::LaneMarkers* mutable_lane_marker();
  ::apollo::perception::LaneMarkers* release_lane_marker();
  void set_allocated_lane_marker(::apollo::perception::LaneMarkers* lane_marker);

  // optional .apollo.perception.CIPVInfo cipv_info = 5;
  bool has_cipv_info() const;
  void clear_cipv_info();
  static const int kCipvInfoFieldNumber = 5;
  const ::apollo::perception::CIPVInfo& cipv_info() const;
  ::apollo::perception::CIPVInfo* mutable_cipv_info();
  ::apollo::perception::CIPVInfo* release_cipv_info();
  void set_allocated_cipv_info(::apollo::perception::CIPVInfo* cipv_info);

  // @@protoc_insertion_point(class_scope:apollo.perception.PerceptionObstacles)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_lane_marker();
  inline void clear_has_lane_marker();
  inline void set_has_cipv_info();
  inline void clear_has_cipv_info();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::PerceptionObstacle > perception_obstacle_;
  ::apollo::common::Header* header_;
  ::apollo::perception::LaneMarkers* lane_marker_;
  ::apollo::perception::CIPVInfo* cipv_info_;
  int error_code_;
  friend void  protobuf_AddDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_AssignDesc_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();
  friend void protobuf_ShutdownFile_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto();

  void InitAsDefaultInstance();
  static PerceptionObstacles* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Point

// optional double x = 1;
inline bool Point::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Point::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Point::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Point::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Point::x() const {
  // @@protoc_insertion_point(field_get:apollo.perception.Point.x)
  return x_;
}
inline void Point::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.Point.x)
}

// optional double y = 2;
inline bool Point::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Point::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Point::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Point::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Point::y() const {
  // @@protoc_insertion_point(field_get:apollo.perception.Point.y)
  return y_;
}
inline void Point::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.Point.y)
}

// optional double z = 3;
inline bool Point::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Point::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Point::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Point::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Point::z() const {
  // @@protoc_insertion_point(field_get:apollo.perception.Point.z)
  return z_;
}
inline void Point::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.Point.z)
}

// -------------------------------------------------------------------

// PerceptionObstacle

// optional int32 id = 1;
inline bool PerceptionObstacle::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PerceptionObstacle::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PerceptionObstacle::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PerceptionObstacle::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 PerceptionObstacle::id() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.id)
  return id_;
}
inline void PerceptionObstacle::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.id)
}

// optional .apollo.perception.Point position = 2;
inline bool PerceptionObstacle::has_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PerceptionObstacle::set_has_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PerceptionObstacle::clear_has_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PerceptionObstacle::clear_position() {
  if (position_ != NULL) position_->::apollo::perception::Point::Clear();
  clear_has_position();
}
inline const ::apollo::perception::Point& PerceptionObstacle::position() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.position)
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
inline ::apollo::perception::Point* PerceptionObstacle::mutable_position() {
  set_has_position();
  if (position_ == NULL) {
    position_ = new ::apollo::perception::Point;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.PerceptionObstacle.position)
  return position_;
}
inline ::apollo::perception::Point* PerceptionObstacle::release_position() {
  // @@protoc_insertion_point(field_release:apollo.perception.PerceptionObstacle.position)
  clear_has_position();
  ::apollo::perception::Point* temp = position_;
  position_ = NULL;
  return temp;
}
inline void PerceptionObstacle::set_allocated_position(::apollo::perception::Point* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.PerceptionObstacle.position)
}

// optional double theta = 3;
inline bool PerceptionObstacle::has_theta() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PerceptionObstacle::set_has_theta() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PerceptionObstacle::clear_has_theta() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PerceptionObstacle::clear_theta() {
  theta_ = 0;
  clear_has_theta();
}
inline double PerceptionObstacle::theta() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.theta)
  return theta_;
}
inline void PerceptionObstacle::set_theta(double value) {
  set_has_theta();
  theta_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.theta)
}

// optional .apollo.perception.Point velocity = 4;
inline bool PerceptionObstacle::has_velocity() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PerceptionObstacle::set_has_velocity() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PerceptionObstacle::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PerceptionObstacle::clear_velocity() {
  if (velocity_ != NULL) velocity_->::apollo::perception::Point::Clear();
  clear_has_velocity();
}
inline const ::apollo::perception::Point& PerceptionObstacle::velocity() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.velocity)
  return velocity_ != NULL ? *velocity_ : *default_instance_->velocity_;
}
inline ::apollo::perception::Point* PerceptionObstacle::mutable_velocity() {
  set_has_velocity();
  if (velocity_ == NULL) {
    velocity_ = new ::apollo::perception::Point;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.PerceptionObstacle.velocity)
  return velocity_;
}
inline ::apollo::perception::Point* PerceptionObstacle::release_velocity() {
  // @@protoc_insertion_point(field_release:apollo.perception.PerceptionObstacle.velocity)
  clear_has_velocity();
  ::apollo::perception::Point* temp = velocity_;
  velocity_ = NULL;
  return temp;
}
inline void PerceptionObstacle::set_allocated_velocity(::apollo::perception::Point* velocity) {
  delete velocity_;
  velocity_ = velocity;
  if (velocity) {
    set_has_velocity();
  } else {
    clear_has_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.PerceptionObstacle.velocity)
}

// optional double length = 5;
inline bool PerceptionObstacle::has_length() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PerceptionObstacle::set_has_length() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PerceptionObstacle::clear_has_length() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PerceptionObstacle::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline double PerceptionObstacle::length() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.length)
  return length_;
}
inline void PerceptionObstacle::set_length(double value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.length)
}

// optional double width = 6;
inline bool PerceptionObstacle::has_width() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PerceptionObstacle::set_has_width() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PerceptionObstacle::clear_has_width() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PerceptionObstacle::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline double PerceptionObstacle::width() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.width)
  return width_;
}
inline void PerceptionObstacle::set_width(double value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.width)
}

// optional double height = 7;
inline bool PerceptionObstacle::has_height() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PerceptionObstacle::set_has_height() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PerceptionObstacle::clear_has_height() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PerceptionObstacle::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline double PerceptionObstacle::height() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.height)
  return height_;
}
inline void PerceptionObstacle::set_height(double value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.height)
}

// repeated .apollo.perception.Point polygon_point = 8;
inline int PerceptionObstacle::polygon_point_size() const {
  return polygon_point_.size();
}
inline void PerceptionObstacle::clear_polygon_point() {
  polygon_point_.Clear();
}
inline const ::apollo::perception::Point& PerceptionObstacle::polygon_point(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.polygon_point)
  return polygon_point_.Get(index);
}
inline ::apollo::perception::Point* PerceptionObstacle::mutable_polygon_point(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.PerceptionObstacle.polygon_point)
  return polygon_point_.Mutable(index);
}
inline ::apollo::perception::Point* PerceptionObstacle::add_polygon_point() {
  // @@protoc_insertion_point(field_add:apollo.perception.PerceptionObstacle.polygon_point)
  return polygon_point_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >*
PerceptionObstacle::mutable_polygon_point() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.PerceptionObstacle.polygon_point)
  return &polygon_point_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >&
PerceptionObstacle::polygon_point() const {
  // @@protoc_insertion_point(field_list:apollo.perception.PerceptionObstacle.polygon_point)
  return polygon_point_;
}

// optional double tracking_time = 9;
inline bool PerceptionObstacle::has_tracking_time() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PerceptionObstacle::set_has_tracking_time() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PerceptionObstacle::clear_has_tracking_time() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PerceptionObstacle::clear_tracking_time() {
  tracking_time_ = 0;
  clear_has_tracking_time();
}
inline double PerceptionObstacle::tracking_time() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.tracking_time)
  return tracking_time_;
}
inline void PerceptionObstacle::set_tracking_time(double value) {
  set_has_tracking_time();
  tracking_time_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.tracking_time)
}

// optional .apollo.perception.PerceptionObstacle.Type type = 10;
inline bool PerceptionObstacle::has_type() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void PerceptionObstacle::set_has_type() {
  _has_bits_[0] |= 0x00000200u;
}
inline void PerceptionObstacle::clear_has_type() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void PerceptionObstacle::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::apollo::perception::PerceptionObstacle_Type PerceptionObstacle::type() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.type)
  return static_cast< ::apollo::perception::PerceptionObstacle_Type >(type_);
}
inline void PerceptionObstacle::set_type(::apollo::perception::PerceptionObstacle_Type value) {
  assert(::apollo::perception::PerceptionObstacle_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.type)
}

// optional double timestamp = 11;
inline bool PerceptionObstacle::has_timestamp() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void PerceptionObstacle::set_has_timestamp() {
  _has_bits_[0] |= 0x00000400u;
}
inline void PerceptionObstacle::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void PerceptionObstacle::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline double PerceptionObstacle::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.timestamp)
  return timestamp_;
}
inline void PerceptionObstacle::set_timestamp(double value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.timestamp)
}

// repeated double point_cloud = 12 [packed = true];
inline int PerceptionObstacle::point_cloud_size() const {
  return point_cloud_.size();
}
inline void PerceptionObstacle::clear_point_cloud() {
  point_cloud_.Clear();
}
inline double PerceptionObstacle::point_cloud(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.point_cloud)
  return point_cloud_.Get(index);
}
inline void PerceptionObstacle::set_point_cloud(int index, double value) {
  point_cloud_.Set(index, value);
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.point_cloud)
}
inline void PerceptionObstacle::add_point_cloud(double value) {
  point_cloud_.Add(value);
  // @@protoc_insertion_point(field_add:apollo.perception.PerceptionObstacle.point_cloud)
}
inline const ::google::protobuf::RepeatedField< double >&
PerceptionObstacle::point_cloud() const {
  // @@protoc_insertion_point(field_list:apollo.perception.PerceptionObstacle.point_cloud)
  return point_cloud_;
}
inline ::google::protobuf::RepeatedField< double >*
PerceptionObstacle::mutable_point_cloud() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.PerceptionObstacle.point_cloud)
  return &point_cloud_;
}

// optional double confidence = 13 [default = 1];
inline bool PerceptionObstacle::has_confidence() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void PerceptionObstacle::set_has_confidence() {
  _has_bits_[0] |= 0x00001000u;
}
inline void PerceptionObstacle::clear_has_confidence() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void PerceptionObstacle::clear_confidence() {
  confidence_ = 1;
  clear_has_confidence();
}
inline double PerceptionObstacle::confidence() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.confidence)
  return confidence_;
}
inline void PerceptionObstacle::set_confidence(double value) {
  set_has_confidence();
  confidence_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.confidence)
}

// optional .apollo.perception.PerceptionObstacle.ConfidenceType confidence_type = 14 [default = CONFIDENCE_CNN];
inline bool PerceptionObstacle::has_confidence_type() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void PerceptionObstacle::set_has_confidence_type() {
  _has_bits_[0] |= 0x00002000u;
}
inline void PerceptionObstacle::clear_has_confidence_type() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void PerceptionObstacle::clear_confidence_type() {
  confidence_type_ = 1;
  clear_has_confidence_type();
}
inline ::apollo::perception::PerceptionObstacle_ConfidenceType PerceptionObstacle::confidence_type() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.confidence_type)
  return static_cast< ::apollo::perception::PerceptionObstacle_ConfidenceType >(confidence_type_);
}
inline void PerceptionObstacle::set_confidence_type(::apollo::perception::PerceptionObstacle_ConfidenceType value) {
  assert(::apollo::perception::PerceptionObstacle_ConfidenceType_IsValid(value));
  set_has_confidence_type();
  confidence_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacle.confidence_type)
}

// repeated .apollo.perception.Point drops = 15;
inline int PerceptionObstacle::drops_size() const {
  return drops_.size();
}
inline void PerceptionObstacle::clear_drops() {
  drops_.Clear();
}
inline const ::apollo::perception::Point& PerceptionObstacle::drops(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacle.drops)
  return drops_.Get(index);
}
inline ::apollo::perception::Point* PerceptionObstacle::mutable_drops(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.PerceptionObstacle.drops)
  return drops_.Mutable(index);
}
inline ::apollo::perception::Point* PerceptionObstacle::add_drops() {
  // @@protoc_insertion_point(field_add:apollo.perception.PerceptionObstacle.drops)
  return drops_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >*
PerceptionObstacle::mutable_drops() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.PerceptionObstacle.drops)
  return &drops_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >&
PerceptionObstacle::drops() const {
  // @@protoc_insertion_point(field_list:apollo.perception.PerceptionObstacle.drops)
  return drops_;
}

// -------------------------------------------------------------------

// CIPVInfo

// optional int32 cipv_id = 1;
inline bool CIPVInfo::has_cipv_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CIPVInfo::set_has_cipv_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CIPVInfo::clear_has_cipv_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CIPVInfo::clear_cipv_id() {
  cipv_id_ = 0;
  clear_has_cipv_id();
}
inline ::google::protobuf::int32 CIPVInfo::cipv_id() const {
  // @@protoc_insertion_point(field_get:apollo.perception.CIPVInfo.cipv_id)
  return cipv_id_;
}
inline void CIPVInfo::set_cipv_id(::google::protobuf::int32 value) {
  set_has_cipv_id();
  cipv_id_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.CIPVInfo.cipv_id)
}

// repeated int32 potential_cipv_id = 2;
inline int CIPVInfo::potential_cipv_id_size() const {
  return potential_cipv_id_.size();
}
inline void CIPVInfo::clear_potential_cipv_id() {
  potential_cipv_id_.Clear();
}
inline ::google::protobuf::int32 CIPVInfo::potential_cipv_id(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.CIPVInfo.potential_cipv_id)
  return potential_cipv_id_.Get(index);
}
inline void CIPVInfo::set_potential_cipv_id(int index, ::google::protobuf::int32 value) {
  potential_cipv_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:apollo.perception.CIPVInfo.potential_cipv_id)
}
inline void CIPVInfo::add_potential_cipv_id(::google::protobuf::int32 value) {
  potential_cipv_id_.Add(value);
  // @@protoc_insertion_point(field_add:apollo.perception.CIPVInfo.potential_cipv_id)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CIPVInfo::potential_cipv_id() const {
  // @@protoc_insertion_point(field_list:apollo.perception.CIPVInfo.potential_cipv_id)
  return potential_cipv_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CIPVInfo::mutable_potential_cipv_id() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.CIPVInfo.potential_cipv_id)
  return &potential_cipv_id_;
}

// -------------------------------------------------------------------

// LaneMarker

// optional .apollo.hdmap.LaneBoundaryType.Type lane_type = 1;
inline bool LaneMarker::has_lane_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LaneMarker::set_has_lane_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LaneMarker::clear_has_lane_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LaneMarker::clear_lane_type() {
  lane_type_ = 0;
  clear_has_lane_type();
}
inline ::apollo::hdmap::LaneBoundaryType_Type LaneMarker::lane_type() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.lane_type)
  return static_cast< ::apollo::hdmap::LaneBoundaryType_Type >(lane_type_);
}
inline void LaneMarker::set_lane_type(::apollo::hdmap::LaneBoundaryType_Type value) {
  assert(::apollo::hdmap::LaneBoundaryType_Type_IsValid(value));
  set_has_lane_type();
  lane_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.lane_type)
}

// optional double quality = 2;
inline bool LaneMarker::has_quality() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LaneMarker::set_has_quality() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LaneMarker::clear_has_quality() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LaneMarker::clear_quality() {
  quality_ = 0;
  clear_has_quality();
}
inline double LaneMarker::quality() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.quality)
  return quality_;
}
inline void LaneMarker::set_quality(double value) {
  set_has_quality();
  quality_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.quality)
}

// optional int32 model_degree = 3;
inline bool LaneMarker::has_model_degree() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LaneMarker::set_has_model_degree() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LaneMarker::clear_has_model_degree() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LaneMarker::clear_model_degree() {
  model_degree_ = 0;
  clear_has_model_degree();
}
inline ::google::protobuf::int32 LaneMarker::model_degree() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.model_degree)
  return model_degree_;
}
inline void LaneMarker::set_model_degree(::google::protobuf::int32 value) {
  set_has_model_degree();
  model_degree_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.model_degree)
}

// optional double c0_position = 4;
inline bool LaneMarker::has_c0_position() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LaneMarker::set_has_c0_position() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LaneMarker::clear_has_c0_position() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LaneMarker::clear_c0_position() {
  c0_position_ = 0;
  clear_has_c0_position();
}
inline double LaneMarker::c0_position() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.c0_position)
  return c0_position_;
}
inline void LaneMarker::set_c0_position(double value) {
  set_has_c0_position();
  c0_position_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.c0_position)
}

// optional double c1_heading_angle = 5;
inline bool LaneMarker::has_c1_heading_angle() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LaneMarker::set_has_c1_heading_angle() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LaneMarker::clear_has_c1_heading_angle() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LaneMarker::clear_c1_heading_angle() {
  c1_heading_angle_ = 0;
  clear_has_c1_heading_angle();
}
inline double LaneMarker::c1_heading_angle() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.c1_heading_angle)
  return c1_heading_angle_;
}
inline void LaneMarker::set_c1_heading_angle(double value) {
  set_has_c1_heading_angle();
  c1_heading_angle_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.c1_heading_angle)
}

// optional double c2_curvature = 6;
inline bool LaneMarker::has_c2_curvature() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void LaneMarker::set_has_c2_curvature() {
  _has_bits_[0] |= 0x00000020u;
}
inline void LaneMarker::clear_has_c2_curvature() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void LaneMarker::clear_c2_curvature() {
  c2_curvature_ = 0;
  clear_has_c2_curvature();
}
inline double LaneMarker::c2_curvature() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.c2_curvature)
  return c2_curvature_;
}
inline void LaneMarker::set_c2_curvature(double value) {
  set_has_c2_curvature();
  c2_curvature_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.c2_curvature)
}

// optional double c3_curvature_derivative = 7;
inline bool LaneMarker::has_c3_curvature_derivative() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void LaneMarker::set_has_c3_curvature_derivative() {
  _has_bits_[0] |= 0x00000040u;
}
inline void LaneMarker::clear_has_c3_curvature_derivative() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void LaneMarker::clear_c3_curvature_derivative() {
  c3_curvature_derivative_ = 0;
  clear_has_c3_curvature_derivative();
}
inline double LaneMarker::c3_curvature_derivative() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.c3_curvature_derivative)
  return c3_curvature_derivative_;
}
inline void LaneMarker::set_c3_curvature_derivative(double value) {
  set_has_c3_curvature_derivative();
  c3_curvature_derivative_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.c3_curvature_derivative)
}

// optional double view_range = 8;
inline bool LaneMarker::has_view_range() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void LaneMarker::set_has_view_range() {
  _has_bits_[0] |= 0x00000080u;
}
inline void LaneMarker::clear_has_view_range() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void LaneMarker::clear_view_range() {
  view_range_ = 0;
  clear_has_view_range();
}
inline double LaneMarker::view_range() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.view_range)
  return view_range_;
}
inline void LaneMarker::set_view_range(double value) {
  set_has_view_range();
  view_range_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.view_range)
}

// optional double longitude_start = 9;
inline bool LaneMarker::has_longitude_start() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void LaneMarker::set_has_longitude_start() {
  _has_bits_[0] |= 0x00000100u;
}
inline void LaneMarker::clear_has_longitude_start() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void LaneMarker::clear_longitude_start() {
  longitude_start_ = 0;
  clear_has_longitude_start();
}
inline double LaneMarker::longitude_start() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.longitude_start)
  return longitude_start_;
}
inline void LaneMarker::set_longitude_start(double value) {
  set_has_longitude_start();
  longitude_start_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.longitude_start)
}

// optional double longitude_end = 10;
inline bool LaneMarker::has_longitude_end() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void LaneMarker::set_has_longitude_end() {
  _has_bits_[0] |= 0x00000200u;
}
inline void LaneMarker::clear_has_longitude_end() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void LaneMarker::clear_longitude_end() {
  longitude_end_ = 0;
  clear_has_longitude_end();
}
inline double LaneMarker::longitude_end() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarker.longitude_end)
  return longitude_end_;
}
inline void LaneMarker::set_longitude_end(double value) {
  set_has_longitude_end();
  longitude_end_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.LaneMarker.longitude_end)
}

// -------------------------------------------------------------------

// LaneMarkers

// optional .apollo.perception.LaneMarker left_lane_marker = 1;
inline bool LaneMarkers::has_left_lane_marker() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LaneMarkers::set_has_left_lane_marker() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LaneMarkers::clear_has_left_lane_marker() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LaneMarkers::clear_left_lane_marker() {
  if (left_lane_marker_ != NULL) left_lane_marker_->::apollo::perception::LaneMarker::Clear();
  clear_has_left_lane_marker();
}
inline const ::apollo::perception::LaneMarker& LaneMarkers::left_lane_marker() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarkers.left_lane_marker)
  return left_lane_marker_ != NULL ? *left_lane_marker_ : *default_instance_->left_lane_marker_;
}
inline ::apollo::perception::LaneMarker* LaneMarkers::mutable_left_lane_marker() {
  set_has_left_lane_marker();
  if (left_lane_marker_ == NULL) {
    left_lane_marker_ = new ::apollo::perception::LaneMarker;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.LaneMarkers.left_lane_marker)
  return left_lane_marker_;
}
inline ::apollo::perception::LaneMarker* LaneMarkers::release_left_lane_marker() {
  // @@protoc_insertion_point(field_release:apollo.perception.LaneMarkers.left_lane_marker)
  clear_has_left_lane_marker();
  ::apollo::perception::LaneMarker* temp = left_lane_marker_;
  left_lane_marker_ = NULL;
  return temp;
}
inline void LaneMarkers::set_allocated_left_lane_marker(::apollo::perception::LaneMarker* left_lane_marker) {
  delete left_lane_marker_;
  left_lane_marker_ = left_lane_marker;
  if (left_lane_marker) {
    set_has_left_lane_marker();
  } else {
    clear_has_left_lane_marker();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.LaneMarkers.left_lane_marker)
}

// optional .apollo.perception.LaneMarker right_lane_marker = 2;
inline bool LaneMarkers::has_right_lane_marker() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LaneMarkers::set_has_right_lane_marker() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LaneMarkers::clear_has_right_lane_marker() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LaneMarkers::clear_right_lane_marker() {
  if (right_lane_marker_ != NULL) right_lane_marker_->::apollo::perception::LaneMarker::Clear();
  clear_has_right_lane_marker();
}
inline const ::apollo::perception::LaneMarker& LaneMarkers::right_lane_marker() const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarkers.right_lane_marker)
  return right_lane_marker_ != NULL ? *right_lane_marker_ : *default_instance_->right_lane_marker_;
}
inline ::apollo::perception::LaneMarker* LaneMarkers::mutable_right_lane_marker() {
  set_has_right_lane_marker();
  if (right_lane_marker_ == NULL) {
    right_lane_marker_ = new ::apollo::perception::LaneMarker;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.LaneMarkers.right_lane_marker)
  return right_lane_marker_;
}
inline ::apollo::perception::LaneMarker* LaneMarkers::release_right_lane_marker() {
  // @@protoc_insertion_point(field_release:apollo.perception.LaneMarkers.right_lane_marker)
  clear_has_right_lane_marker();
  ::apollo::perception::LaneMarker* temp = right_lane_marker_;
  right_lane_marker_ = NULL;
  return temp;
}
inline void LaneMarkers::set_allocated_right_lane_marker(::apollo::perception::LaneMarker* right_lane_marker) {
  delete right_lane_marker_;
  right_lane_marker_ = right_lane_marker;
  if (right_lane_marker) {
    set_has_right_lane_marker();
  } else {
    clear_has_right_lane_marker();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.LaneMarkers.right_lane_marker)
}

// repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;
inline int LaneMarkers::next_left_lane_marker_size() const {
  return next_left_lane_marker_.size();
}
inline void LaneMarkers::clear_next_left_lane_marker() {
  next_left_lane_marker_.Clear();
}
inline const ::apollo::perception::LaneMarker& LaneMarkers::next_left_lane_marker(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarkers.next_left_lane_marker)
  return next_left_lane_marker_.Get(index);
}
inline ::apollo::perception::LaneMarker* LaneMarkers::mutable_next_left_lane_marker(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.LaneMarkers.next_left_lane_marker)
  return next_left_lane_marker_.Mutable(index);
}
inline ::apollo::perception::LaneMarker* LaneMarkers::add_next_left_lane_marker() {
  // @@protoc_insertion_point(field_add:apollo.perception.LaneMarkers.next_left_lane_marker)
  return next_left_lane_marker_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker >*
LaneMarkers::mutable_next_left_lane_marker() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.LaneMarkers.next_left_lane_marker)
  return &next_left_lane_marker_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker >&
LaneMarkers::next_left_lane_marker() const {
  // @@protoc_insertion_point(field_list:apollo.perception.LaneMarkers.next_left_lane_marker)
  return next_left_lane_marker_;
}

// repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;
inline int LaneMarkers::next_right_lane_marker_size() const {
  return next_right_lane_marker_.size();
}
inline void LaneMarkers::clear_next_right_lane_marker() {
  next_right_lane_marker_.Clear();
}
inline const ::apollo::perception::LaneMarker& LaneMarkers::next_right_lane_marker(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.LaneMarkers.next_right_lane_marker)
  return next_right_lane_marker_.Get(index);
}
inline ::apollo::perception::LaneMarker* LaneMarkers::mutable_next_right_lane_marker(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.LaneMarkers.next_right_lane_marker)
  return next_right_lane_marker_.Mutable(index);
}
inline ::apollo::perception::LaneMarker* LaneMarkers::add_next_right_lane_marker() {
  // @@protoc_insertion_point(field_add:apollo.perception.LaneMarkers.next_right_lane_marker)
  return next_right_lane_marker_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker >*
LaneMarkers::mutable_next_right_lane_marker() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.LaneMarkers.next_right_lane_marker)
  return &next_right_lane_marker_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::LaneMarker >&
LaneMarkers::next_right_lane_marker() const {
  // @@protoc_insertion_point(field_list:apollo.perception.LaneMarkers.next_right_lane_marker)
  return next_right_lane_marker_;
}

// -------------------------------------------------------------------

// PerceptionObstacles

// repeated .apollo.perception.PerceptionObstacle perception_obstacle = 1;
inline int PerceptionObstacles::perception_obstacle_size() const {
  return perception_obstacle_.size();
}
inline void PerceptionObstacles::clear_perception_obstacle() {
  perception_obstacle_.Clear();
}
inline const ::apollo::perception::PerceptionObstacle& PerceptionObstacles::perception_obstacle(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacles.perception_obstacle)
  return perception_obstacle_.Get(index);
}
inline ::apollo::perception::PerceptionObstacle* PerceptionObstacles::mutable_perception_obstacle(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.PerceptionObstacles.perception_obstacle)
  return perception_obstacle_.Mutable(index);
}
inline ::apollo::perception::PerceptionObstacle* PerceptionObstacles::add_perception_obstacle() {
  // @@protoc_insertion_point(field_add:apollo.perception.PerceptionObstacles.perception_obstacle)
  return perception_obstacle_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::PerceptionObstacle >*
PerceptionObstacles::mutable_perception_obstacle() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.PerceptionObstacles.perception_obstacle)
  return &perception_obstacle_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::PerceptionObstacle >&
PerceptionObstacles::perception_obstacle() const {
  // @@protoc_insertion_point(field_list:apollo.perception.PerceptionObstacles.perception_obstacle)
  return perception_obstacle_;
}

// optional .apollo.common.Header header = 2;
inline bool PerceptionObstacles::has_header() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PerceptionObstacles::set_has_header() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PerceptionObstacles::clear_has_header() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PerceptionObstacles::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& PerceptionObstacles::header() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacles.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::apollo::common::Header* PerceptionObstacles::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::apollo::common::Header;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.PerceptionObstacles.header)
  return header_;
}
inline ::apollo::common::Header* PerceptionObstacles::release_header() {
  // @@protoc_insertion_point(field_release:apollo.perception.PerceptionObstacles.header)
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void PerceptionObstacles::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.PerceptionObstacles.header)
}

// optional .apollo.common.ErrorCode error_code = 3 [default = OK];
inline bool PerceptionObstacles::has_error_code() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PerceptionObstacles::set_has_error_code() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PerceptionObstacles::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PerceptionObstacles::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::apollo::common::ErrorCode PerceptionObstacles::error_code() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacles.error_code)
  return static_cast< ::apollo::common::ErrorCode >(error_code_);
}
inline void PerceptionObstacles::set_error_code(::apollo::common::ErrorCode value) {
  assert(::apollo::common::ErrorCode_IsValid(value));
  set_has_error_code();
  error_code_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.PerceptionObstacles.error_code)
}

// optional .apollo.perception.LaneMarkers lane_marker = 4;
inline bool PerceptionObstacles::has_lane_marker() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PerceptionObstacles::set_has_lane_marker() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PerceptionObstacles::clear_has_lane_marker() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PerceptionObstacles::clear_lane_marker() {
  if (lane_marker_ != NULL) lane_marker_->::apollo::perception::LaneMarkers::Clear();
  clear_has_lane_marker();
}
inline const ::apollo::perception::LaneMarkers& PerceptionObstacles::lane_marker() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacles.lane_marker)
  return lane_marker_ != NULL ? *lane_marker_ : *default_instance_->lane_marker_;
}
inline ::apollo::perception::LaneMarkers* PerceptionObstacles::mutable_lane_marker() {
  set_has_lane_marker();
  if (lane_marker_ == NULL) {
    lane_marker_ = new ::apollo::perception::LaneMarkers;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.PerceptionObstacles.lane_marker)
  return lane_marker_;
}
inline ::apollo::perception::LaneMarkers* PerceptionObstacles::release_lane_marker() {
  // @@protoc_insertion_point(field_release:apollo.perception.PerceptionObstacles.lane_marker)
  clear_has_lane_marker();
  ::apollo::perception::LaneMarkers* temp = lane_marker_;
  lane_marker_ = NULL;
  return temp;
}
inline void PerceptionObstacles::set_allocated_lane_marker(::apollo::perception::LaneMarkers* lane_marker) {
  delete lane_marker_;
  lane_marker_ = lane_marker;
  if (lane_marker) {
    set_has_lane_marker();
  } else {
    clear_has_lane_marker();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.PerceptionObstacles.lane_marker)
}

// optional .apollo.perception.CIPVInfo cipv_info = 5;
inline bool PerceptionObstacles::has_cipv_info() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PerceptionObstacles::set_has_cipv_info() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PerceptionObstacles::clear_has_cipv_info() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PerceptionObstacles::clear_cipv_info() {
  if (cipv_info_ != NULL) cipv_info_->::apollo::perception::CIPVInfo::Clear();
  clear_has_cipv_info();
}
inline const ::apollo::perception::CIPVInfo& PerceptionObstacles::cipv_info() const {
  // @@protoc_insertion_point(field_get:apollo.perception.PerceptionObstacles.cipv_info)
  return cipv_info_ != NULL ? *cipv_info_ : *default_instance_->cipv_info_;
}
inline ::apollo::perception::CIPVInfo* PerceptionObstacles::mutable_cipv_info() {
  set_has_cipv_info();
  if (cipv_info_ == NULL) {
    cipv_info_ = new ::apollo::perception::CIPVInfo;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.PerceptionObstacles.cipv_info)
  return cipv_info_;
}
inline ::apollo::perception::CIPVInfo* PerceptionObstacles::release_cipv_info() {
  // @@protoc_insertion_point(field_release:apollo.perception.PerceptionObstacles.cipv_info)
  clear_has_cipv_info();
  ::apollo::perception::CIPVInfo* temp = cipv_info_;
  cipv_info_ = NULL;
  return temp;
}
inline void PerceptionObstacles::set_allocated_cipv_info(::apollo::perception::CIPVInfo* cipv_info) {
  delete cipv_info_;
  cipv_info_ = cipv_info;
  if (cipv_info) {
    set_has_cipv_info();
  } else {
    clear_has_cipv_info();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.PerceptionObstacles.cipv_info)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace perception
}  // namespace apollo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::perception::PerceptionObstacle_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::perception::PerceptionObstacle_Type>() {
  return ::apollo::perception::PerceptionObstacle_Type_descriptor();
}
template <> struct is_proto_enum< ::apollo::perception::PerceptionObstacle_ConfidenceType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::perception::PerceptionObstacle_ConfidenceType>() {
  return ::apollo::perception::PerceptionObstacle_ConfidenceType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2fperception_2fproto_2fperception_5fobstacle_2eproto__INCLUDED
