
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "status",
    hdrs = [
        "status.h",
    ],
    deps = [
        "//modules/common/proto:error_code_proto",
        "@com_google_protobuf//:protobuf",
    ],
)


